// COURSE
export const SET_DETAIL_COURSE = "SET_DETAIL_COURSE";
export const SET_DATA_COURSE = "SET_DATA_COURSE";
export const DELETE_COURSE = "DELETE_COURSE"
export const TOTAL_POINT_RATE = "TOTAL_POINT_RATE"
// USER
export const FETCH_USER_LOGIN = "FETCH_USER_LOGIN";
